### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by croaker000** [nicolas-dutertry/letsimapd#1]
couriertls: /etc/letsencrypt/live/HOSTNAME/imapd.pem: Permission denied

After following instructions.

Manually setting chown to root:courier and chmod to 640 makes no difference

**Comment by croaker000** [comment]
It seems it needs courier:courier permissions on an Ubuntu server

**Comment by nicolas-dutertry** [comment]
The permission issue is on /etc/letsencrypt/live directory.
You can run the following commands as root :

    groupadd letsencrypt
    usermod -a -G letsencrypt courier
    chgrp letsencrypt /etc/letsencrypt/live
    chmod g+rx /etc/letsencrypt/live
